### ISSUE TITLE
Fullstack Proposal checklist

### ISSUE THREAD

**Issue by minucos** [ahhchooey/Note#1]
Hi Alex

Below is a checklist for you to use when putting together your project proposal this week.

We will meet on thursday or friday this week to go over your proposal, discuss a plan for next week, and make any tweaks.

I will be reviewing and checking off this list myself tomorrow and each day as you complete the plan, and will add any notes for changes.

# Wiki Page Home
- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page
## Comments

All good, nothing to change here!

---
# MVP List
- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes two to three detailed bullets on functionality and presentation of feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points
## Comments

Nice and detailed! I would tweak the order of your MVPs as below:

1) User Auth
2) Deploying to Heroku
3..6) 4 of your MVPs
7) Production README
8..11) Marked as BONUS features

We can discuss which of your MVPs to place in 3-6 and 8-11 when we meet today.

---
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments

All looks great! We can discuss this when we meet today to clear up any of the sections you've added question marks to

---
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments

Looks good! The only change I would make is removing note/tag id arrays from your users/notes/etc. These should not be needed. I would instead include a slice of state referencing the joins table that links these, then use a selector when you want to gather the tags for a particular note.

We can go over this in more detail today
 
---
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments

Look great, good job!

---
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments

Look good!

**Comment by minucos** [comment]
Added some comments above, and ticked off what is complete.

Only a couple minor things to adjust, so we can discuss these later today
