### ISSUE TITLE
1st MVP: User Auth checklist

### ISSUE THREAD

**Issue by minucos** [ahhchooey/Note#2]
Hi Alex

Below is a checklist for you to work off for your first MVP (User Auth):

user auth 
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components
- [ ] Styling
  - [ ] When errors are displayed, the form adjusts properly
- [ ] Smooth, bug free navigation
  - [ ] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [ ] Errors should display for both `/signup` and`/login`.
- [ ] Adequate and appropriate seeds
  - [ ] Demo Login Works

Once you are happy with your auth and your site is up on heroku I'll work through the list and close it out

**Comment by ahhchooey** [comment]
so as we went over in lecture hall, my user auth is completely done, i think, maybe

**Comment by minucos** [comment]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [ ] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in


## Style

- [x] The site should look like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds


## COMMENTS

Looks great! 

Only a couple minor notes for you to fix:

- ### Functional
  -  [ ] Signup errors not displaying. If I attempt to sign up with an email that is already taken, it does not display any error message.

- ### Styling
  - [ ] Please apply some styling on hover for your login and signup buttons in your splash page's navbar. Just change the font and border colors to be darker/brighter

**Comment by minucos** [comment]
MVP approved and closed!
